name: '.NET Continuous Integration'
description: 'Build and test .NET projects'
branding:
  icon: 'settings'
  color: 'green'
inputs:
  dotnet-version:
    description: 'The .NET SDK version to use'
    required: false
    default: '6.0'
  build-configuration:
    description: 'Configuration to use for building the project'
    required: false
    default: 'Release'
  test-verbosity:
    description: 'Set the verbosity of test results'
    required: false
    default: 'normal'
runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build
      run: dotnet build --no-restore --configuration ${{ inputs.build-configuration }}
      shell: bash

    - name: Run tests
      run: dotnet test --no-build --configuration ${{ inputs.build-configuration }} --verbosity ${{ inputs.test-verbosity }}
      shell: bash
