name: Test .NET Continuous Integration

on:
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0'
    
    - name: Setup Test .NET Project
      run: |
        mkdir src
        dotnet new sln -n HelloWorld
        dotnet new classlib -n HelloWorld -o src/HelloWorld
        dotnet new mstest -n HelloWorld.Tests -o src/HelloWorld.Tests
        dotnet sln HelloWorld.sln add src/HelloWorld/HelloWorld.csproj
        dotnet sln HelloWorld.sln add src/HelloWorld.Tests/HelloWorld.Tests.csproj
        echo "namespace HelloWorld { public class HelloWorld { public string SayHello() => \"Hello World\"; }}" > src/HelloWorld/HelloWorld.cs
        echo "using Microsoft.VisualStudio.TestTools.UnitTesting; namespace HelloWorld.Tests { [TestClass] public class HelloWorldTests { [TestMethod] public void TestHelloWorld() { var helloWorld = new HelloWorld.HelloWorld(); Assert.AreEqual(\"Hello World\", helloWorld.SayHello()); }}" > src/HelloWorld.Tests/HelloWorldTests.cs

    - name: Quick Check
      run: |
        pwd
        ls    

    - name: Build and Test using Custom Action
      uses: ./action.yaml
